spring.application.name=MySpringWeb
server.port=8080

# Database Configuration
spring.datasource.driver-class-name= com.mysql.jdbc.Driver
spring.datasource.url= jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.datasource.username= 4DsA3VzbU8UVGZm.root
spring.datasource.password= aIGYioJ5G478m5j2

#JPA Configuration - Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true